const products = [
  {
    id: 0,
    name: "Sweatshirt 0",
    manufacturer: "H&M",
    price: 59.99,
    instock: 100,
    description: "Beige sweatshirt",
    imgSrc: "./assets/beige-sweatshirt.jpg",
  },
  {
    id: 1,
    name: "Sweater 1",
    manufacturer: "H&M",
    price: 29.99,
    instock: 1000,
    description: "Black sweater",
    imgSrc: "./assets/black-sweater.jpg",
  },
  {
    id: 2,
    name: "Sweatshirt 2",
    manufacturer: "Reserved",
    price: 19.99,
    instock: 100,
    description: "Black sweatshirt.",
    imgSrc: "./assets/black-sweatshirt.jpg",
  },
  {
    id: 3,
    name: "T-shirt 3",
    manufacturer: "Reserved",
    price: 29.99,
    instock: 10,
    description: "Black T-Shirt",
    imgSrc: "./assets/black-tshirt.jpg",
  },
  {
    id: 4,
    name: "Sweater 4",
    manufacturer: "Reserved",
    price: 29.99,
    instock: 100,
    description: "Blue Sweater",
    imgSrc: "./assets/blue-sweater.jpg",
  },
  {
    id: 5,
    name: "Sweater 5",
    manufacturer: "New Yorker",
    price: 59.99,
    instock: 100,
    description: "Brown sweater",
    imgSrc: "./assets/brown-sweater.jpg",
  },
  {
    id: 6,
    name: "Sweatshirt 6",
    manufacturer: "New Yorker",
    price: 59.99,
    instock: 100,
    description: "Grey sweatshirt",
    imgSrc: "./assets/grey-sweatshirt.jpg",
  },
  {
    id: 7,
    name: "Sweater 7",
    manufacturer: "New Yorker",
    price: 59.99,
    instock: 100,
    description: "Pink sweater",
    imgSrc: "./assets/pink-sweater.jpg",
  },
  {
    id: 8,
    name: "Sweater 8",
    manufacturer: "Bershka",
    price: 59.99,
    instock: 100,
    description: "Red sweater",
    imgSrc: "./assets/red-sweater.jpg",
  },
  {
    id: 9,
    name: "Sweater 9",
    manufacturer: "Bershka",
    price: 59.99,
    instock: 100,
    description: "Yellow sweater",
    imgSrc: "./assets/yellow-sweater.jpg",
  },
  {
    id: 10,
    name: "T-Shirt 10",
    manufacturer: "Bershka",
    price: 29.99,
    instock: 100,
    description: "White T-shirt",
    imgSrc: "./assets/white-tshirt.jpg",
  },
  {
    id: 11,
    name: "Sweater 11",
    manufacturer: "Bershka",
    price: 79.99,
    instock: 100,
    description: "Green Sweater",
    imgSrc: "./assets/green-sweater.jpg",
  },
];
